# Generated by Django 3.2.8 on 2021-12-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_rasm_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasm',
            name='photo',
            field=models.FileField(upload_to='static/media/'),
        ),
    ]
